
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class softdrink extends javax.swing.JFrame {

    /**
     * Creates new form softdrink
     */
    public softdrink() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        j6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student\\Desktop\\New folder (2)\\chilled-cold-drink-500x500.jpg")); // NOI18N
        jLabel2.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j1.setText("0");
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 50, 30));

        j2.setText("0");
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, -1));

        j3.setText("0");
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 50, -1));

        j4.setText("0");
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 50, -1));

        j5.setText("0");
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 50, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton1.setText("Add To Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel3.setText("Total amt");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 274, -1, -1));

        j6.setEditable(false);
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 274, 92, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton2.setText("beers");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 170, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton6.setText("menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 170, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton3.setText("hotbeverages");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 170, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton4.setText("Generate Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, 70));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton5.setText("Hookah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 170, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabel5.setText("QTY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, -1));

        c1.setBackground(new java.awt.Color(255, 255, 255));
        c1.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        c1.setText("Redbull");
        c1.setOpaque(false);
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 170, -1));

        c2.setBackground(new java.awt.Color(255, 255, 255));
        c2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        c2.setText("Orangina");
        c2.setOpaque(false);
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 170, -1));

        c3.setBackground(new java.awt.Color(255, 255, 255));
        c3.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        c3.setText("Ginger Ale");
        c3.setOpaque(false);
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 130, -1));

        c4.setBackground(new java.awt.Color(255, 255, 255));
        c4.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        c4.setText("Iced Tea");
        c4.setOpaque(false);
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, -1));

        c5.setBackground(new java.awt.Color(255, 255, 255));
        c5.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        c5.setText("Sparkling Water");
        c5.setOpaque(false);
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 190, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student\\Desktop\\New folder (2)\\chilled-cold-drink-500x500.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -10, 550, 460));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 200, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int item=0;
String cat="Soft Drink";
int q1=0,q2=0,q3=0,q4=0,q5=0,amt1=0,amt2=0,amt3=0,amt4=0,amt5=0;
 double total=0.0;
    q1=Integer.parseInt(j1.getText());
    q2=Integer.parseInt(j2.getText());
        q3=Integer.parseInt(j3.getText());
        q4=Integer.parseInt(j4.getText());
        q5=Integer.parseInt(j5.getText());
 
        if(c2.isSelected())
            amt2=q2*100;
        if(c1.isSelected())
   amt1=q1*150;
        if(c3.isSelected())
   amt3=q3*120;
        if(c4.isSelected())
   amt4=q4*110;
        if(c5.isSelected())
   amt5=q5*120;

total=amt1+amt2+amt3+amt4+amt5;
j6.setText(" "+total);
         if(c1.isSelected())
         {
             try
        {Class.forName("java.sql.DriverManager");
         Connection con;
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/scorpian","root","1234");
         String sql;
                 String scat="Red bull";

         sql="insert into menu values('"+cat+"','"+scat+"','"+q1+"',"+amt1+")";
         Statement st=con.createStatement();
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(null,"Red bull added");

        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null,e.getMessage());
        }
         }
if(c2.isSelected())
         {
             try
        {Class.forName("java.sql.DriverManager");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scorpian","root","1234");
         String sql;
                 String scat="Orangina";

         sql="insert into menu values('"+cat+"','"+scat+"','"+q2+"',"+amt2+")";
         Statement st=con.createStatement();
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(null,"Orangina added");

        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null,e.getMessage());
        }
         }
if(c3.isSelected())
         {
             try
        {Class.forName("java.sql.DriverManager");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scorpian","root","1234");
         String sql;
                 String scat="Ginger Ale";
                
         sql="insert into menu values('"+cat+"','"+scat+"','"+q3+"',"+amt3+")";
         Statement st=con.createStatement();
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(null,"Ginger Ale added");

        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null,e.getMessage());
        }
         }
if(c4.isSelected())
         {
             try
        {Class.forName("java.sql.DriverManager");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scorpian","root","1234");
         String sql;
                 String scat="Iced Tea";

         sql="insert into menu values('"+cat+"','"+scat+"','"+q4+"',"+amt4+")";
         Statement st=con.createStatement();
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(null,"Iced Tea added");

        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null,e.getMessage());
        }
      }

if(c5.isSelected())
         {
             try
        {Class.forName("java.sql.DriverManager");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scorpian","root","1234");
         String sql;
                 String scat="Sparkling Water";

         sql="insert into menu values('"+cat+"','"+scat+"','"+q5+"',"+amt5+")";
         Statement st=con.createStatement();
         st.executeUpdate(sql);
         JOptionPane.showMessageDialog(null,"Sparkling Water added");

        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null,e.getMessage());
        }
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   finalbill f=new finalbill();
f.setVisible(true);
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   beers f=new beers();
f.setVisible(true);
this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 hotbeverages f=new hotbeverages();
f.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 menu f=new menu();
f.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        hukka f=new hukka();
        f.setVisible(true);
        this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(softdrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(softdrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(softdrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(softdrink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new softdrink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
